/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:af632179-4665-4ca1-a9d9-b285b5818043",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vLUCp6Srn",
    "aws_user_pools_web_client_id": "53gf0bjllh9hubbkm22130spgh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://i43uaszdhbeifojd6dl65xgwcy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-34zkdlphgnaf7mb7osez773d4q"
};


export default awsmobile;
